# pandas
- rows - observations - index = 1
- columns - features  - columns = 0

just like dictionary, using string labels data can be accessed

in index slicing works normally but in labeled slicing, endpoint is included

- df1 = pd.DataFrame(vlist, index=rowList, columns=collist)
- direct access
    - df1[   [list of 'col label only']      ]
    - df1[ slice of row labels only ]

<!-- 
- access rows
    - index (named parameter)
    - df1[ slice of row labels only ]
    - 

- access columns
    - columns (not present for dictionary)
    - df1[   [list of 'col label only']      ] -->

- integer index based access iloc
- df1.iloc[ [0,2,-1,-2] , [1,2,5] ]
    - first arr is for access 0 - rows/indexes
    - second arr is for access 1 - columns
- label based indexing loc
    -

In [1]:
import pandas as pd
import numpy as np

In [2]:
valList = [100,200,300,400]
indexList = ['a','b','c','d']
ps1 = pd.Series(valList, index=indexList)
print(type(ps1)) # <class 'pandas.core.series.Series'>
print(ps1.shape)
print(ps1.index)
ps1

<class 'pandas.core.series.Series'>
(4,)
Index(['a', 'b', 'c', 'd'], dtype='object')

a    100
b    200
c    300
d    400
dtype: int64

In [3]:
md1 = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
ps2 = pd.Series(md1)
ps2.index
ps2.values
type(
ps2.values
)

numpy.ndarray

In [4]:
print(ps2[1:3])      # index slicing works normally with end index not included
print(ps2['b':'c'])  # labeled slicing included the end label as well

b    2
c    3
dtype: int64
b    2
c    3
dtype: int64

In [5]:
ps1 + ps2
ps2 + ps1

a    101.0
b    202.0
c    303.0
d    404.0
e      NaN
dtype: float64

# Data Frames

In [6]:
rowList = ['tata','birla', 'wipro', 'infy']
collist = ['rev', 'exp', 'hq']
vlist=[
    [100,50,'mum'],
    [200,150,'kol'],
    [300,250,'blr'],
    [400,350,'blr']
]
df1 = pd.DataFrame(vlist)
print(df1.index)
print(df1.columns)
print(df1.shape)
print(df1)

RangeIndex(start=0, stop=4, step=1)
RangeIndex(start=0, stop=3, step=1)
(4, 3)
     0    1    2
0  100   50  mum
1  200  150  kol
2  300  250  blr
3  400  350  blr

In [7]:
df1 = pd.DataFrame(vlist, index=rowList, columns=collist)
print(df1.index)
print(df1.columns)
print(df1.shape)
print(df1)

Index(['tata', 'birla', 'wipro', 'infy'], dtype='object')
Index(['rev', 'exp', 'hq'], dtype='object')
(4, 3)
       rev  exp   hq
tata   100   50  mum
birla  200  150  kol
wipro  300  250  blr
infy   400  350  blr

## dict to 
- key - col lable

In [8]:
md1 = {'rev': [100,200,300,400],
       'exp': [50,150,250,350],
       'hq': ['mum','kol','blr','blr']
       }
rowList = ['tata', 'birla', 'wipro', 'infy']
df2 = pd.DataFrame(md1, index=rowList)
df2

# TODO: df using dict of dict

       rev  exp   hq
tata   100   50  mum
birla  200  150  kol
wipro  300  250  blr
infy   400  350  blr

In [96]:
df1 = pd.read_csv('lds1.csv')

df1.shape  # must be 11,10...
df1.index

df1.columns
df1.head()
df1.tail()
df1.tail(3)

df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date
Deccan_Sporting,931,839.80,615,Pvt,154,Hyd,1,SPRT,Services,Mar 1943
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928
Indi_Services,954,733.00,609,Gov,13023,NCR,0,INDI,Services,Mar 1920
Bangalore_Breweries,966,805.00,899,Pvt,119,Blr,1,BREW,Goods,Oct 1971
Bombay_Finance,899,917.00,674,Pub,1443,Mum,0,BFIN,Services,Apr 1925
Chennai_Shipping,992,821.00,665,Pub,899,Che,1,SHIP,Goods,Nov 1930
Eastern_Estates,945,834.23,789,Pvt,1873,Kol,1,EEST,Goods,Jan 1994
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974

In [10]:
df1.info()
df1.describe()
df1.describe(include='object')
df1.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, Deccan_Sporting to Central_Services
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Vol         11 non-null     int64
 1   Rev         11 non-null     float64
 2   Exp         11 non-null     int64
 3   Sector      11 non-null     object
 4   EmpCnt      11 non-null     int64
 5   HQ          11 non-null     object
 6   MNC         11 non-null     int64
 7   StockID     11 non-null     object
 8   GST         11 non-null     object
 9   Start Date  11 non-null     object
dtypes: float64(1), int64(4), object(5)
memory usage: 968.0+ bytes

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date
count,11.000000,11.000000,11.000000,11,11.000000,11,11.000000,11,11,11
unique,NaN,NaN,NaN,3,NaN,6,NaN,11,2,11
top,NaN,NaN,NaN,Pub,NaN,NCR,NaN,SPRT,Services,Mar 1943
freq,NaN,NaN,NaN,5,NaN,3,NaN,1,6,1
mean,940.272727,841.520909,679.909091,NaN,2310.454545,NaN,0.545455,NaN,NaN,NaN
std,28.249216,48.199894,90.097119,NaN,3605.962212,NaN,0.522233,NaN,NaN,NaN
min,899.000000,733.000000,605.000000,NaN,119.000000,NaN,0.000000,NaN,NaN,NaN
25%,928.000000,822.500000,612.000000,NaN,1130.000000,NaN,0.000000,NaN,NaN,NaN
50%,934.000000,839.800000,665.000000,NaN,1443.000000,NaN,1.000000,NaN,NaN,NaN
75%,960.000000,868.950000,682.500000,NaN,1764.500000,NaN,1.000000,NaN,NaN,NaN
max,992.000000,917.000000,899.000000,NaN,13023.000000,NaN,1.000000,NaN,NaN,NaN

# access 

- direct access
    - cols are added to dir(df1) ie obj attributes
    - df1['col label only']
    - df1[   [list of 'col label only']      ]
    - df1[ slice of row labels only ]

In [11]:
# access
df1['Vol']

df1['Vol']
df1[ ['Vol', 'Rev'] ]

df1['Bangalore_Systems':'Chennai_Chemicals']


# df1[]
#

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date
Bangalore_Systems,900,881.6,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950
Chennai_Chemicals,966,863.2,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928

In [101]:
print(df1)
df1.iloc[0,0]
df1.iloc[-1,-1]
df1.iloc[2:5, 3:9]

                     Vol     Rev  Exp Sector  EmpCnt   HQ  MNC StockID  \
Deccan_Sporting      931  839.80  615    Pvt     154  Hyd    1    SPRT
Kolkata_FMCG         925  874.40  676    Pub    1379  Kol    0    KFMC
NCR_Leagles          931  863.50  605    Pub    1935  NCR    0    NCRL
Bangalore_Systems    900  881.60  650    Gov    1361  Blr    0    BSYS
Chennai_Chemicals    966  863.20  608    Pub    1656  Che    1    CHEM
Indi_Services        954  733.00  609    Gov   13023  NCR    0    INDI
Bangalore_Breweries  966  805.00  899    Pvt     119  Blr    1    BREW
Bombay_Finance       899  917.00  674    Pub    1443  Mum    0    BFIN
Chennai_Shipping     992  821.00  665    Pub     899  Che    1    SHIP
Eastern_Estates      945  834.23  789    Pvt    1873  Kol    1    EEST
Central_Services     934  824.00  689    Gov    1573  NCR    1    CSRV

                          GST Start Date
Deccan_Sporting      Services   Mar 1943
Kolkata_FMCG            Goods   Jan 1920
NCR_Leagles          Services   Feb 1960
Bangalore_Systems    Services   Apr 1950
Chennai_Chemicals       Goods   Aug 1928
Indi_Services        Services   Mar 1920
Bangalore_Breweries     Goods   Oct 1971
Bombay_Finance       Services   Apr 1925
Chennai_Shipping        Goods   Nov 1930
Eastern_Estates         Goods   Jan 1994
Central_Services     Services   Jun 1974

                  Sector  EmpCnt   HQ  MNC StockID       GST
NCR_Leagles          Pub    1935  NCR    0    NCRL  Services
Bangalore_Systems    Gov    1361  Blr    0    BSYS  Services
Chennai_Chemicals    Pub    1656  Che    1    CHEM     Goods

In [98]:
df1.iloc[ [0,2,-1,-2] ]

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date
Deccan_Sporting,931,839.80,615,Pvt,154,Hyd,1,SPRT,Services,Mar 1943
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974
Eastern_Estates,945,834.23,789,Pvt,1873,Kol,1,EEST,Goods,Jan 1994

In [105]:
df1.iloc[ [0,2,-1,-2] ]['Vol']

df1.iloc[ [0,2,-1,-2] , [1,2,5] ]

df1.iloc[ 0:5:2, [2,3,-2,-1] ]

df1.iloc[ :, 2:4]

                     Exp Sector
Deccan_Sporting      615    Pvt
Kolkata_FMCG         676    Pub
NCR_Leagles          605    Pub
Bangalore_Systems    650    Gov
Chennai_Chemicals    608    Pub
Indi_Services        609    Gov
Bangalore_Breweries  899    Pvt
Bombay_Finance       674    Pub
Chennai_Shipping     665    Pub
Eastern_Estates      789    Pvt
Central_Services     689    Gov

In [106]:
#labeled based access
df1.loc['Kolkata_FMCG']

Vol                925
Rev              874.4
Exp                676
Sector             Pub
EmpCnt            1379
HQ                 Kol
MNC                  0
StockID           KFMC
GST              Goods
Start Date    Jan 1920
Name: Kolkata_FMCG, dtype: object

In [16]:
# df1.loc['Kolkata_FMCG', 'Gst'] 
# TODO: debug issue

In [17]:
df1.Sector == 'Pub' # boolean series

Deccan_Sporting        False
Kolkata_FMCG            True
NCR_Leagles             True
Bangalore_Systems      False
Chennai_Chemicals       True
Indi_Services          False
Bangalore_Breweries    False
Bombay_Finance          True
Chennai_Shipping        True
Eastern_Estates        False
Central_Services       False
Name: Sector, dtype: bool

In [111]:
df1[(df1.Sector == 'Pub') & (df1.GST == 'Services')] ["Vol"]

# (df1[(df1.Sector == 'Pub') & (df1.GST == 'Services')]) [1:2, 2:3]
# TODO: 


type(df1[(df1.Sector == 'Pub') & (df1.GST == 'Services')])

pandas.core.frame.DataFrame

In [115]:
df1[df1.Rev>df1.Rev.mean()]
# df1.Rev>df1.Rev.mean()

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date
Kolkata_FMCG,925,874.4,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920
NCR_Leagles,931,863.5,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960
Bangalore_Systems,900,881.6,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950
Chennai_Chemicals,966,863.2,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928
Bombay_Finance,899,917.0,674,Pub,1443,Mum,0,BFIN,Services,Apr 1925

In [121]:
df1.loc[df1.Rev>df1.Rev.mean(),"Rev"] = 9999
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date
Deccan_Sporting,931,839.80,615,Pvt,154,Hyd,1,SPRT,Services,Mar 1943
Kolkata_FMCG,925,9999.00,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920
NCR_Leagles,931,9999.00,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960
Bangalore_Systems,900,9999.00,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950
Chennai_Chemicals,966,9999.00,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928
Indi_Services,954,733.00,609,Gov,13023,NCR,0,INDI,Services,Mar 1920
Bangalore_Breweries,966,805.00,899,Pvt,119,Blr,1,BREW,Goods,Oct 1971
Bombay_Finance,899,9999.00,674,Pub,1443,Mum,0,BFIN,Services,Apr 1925
Chennai_Shipping,992,821.00,665,Pub,899,Che,1,SHIP,Goods,Nov 1930
Eastern_Estates,945,834.23,789,Pvt,1873,Kol,1,EEST,Goods,Jan 1994
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974

In [21]:
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date
Deccan_Sporting,931,839.80,615,Pvt,154,Hyd,1,SPRT,Services,Mar 1943
Kolkata_FMCG,925,874.40,676,Pub,1379,Kol,0,KFMC,Goods,Jan 1920
NCR_Leagles,931,863.50,605,Pub,1935,NCR,0,NCRL,Services,Feb 1960
Bangalore_Systems,900,881.60,650,Gov,1361,Blr,0,BSYS,Services,Apr 1950
Chennai_Chemicals,966,863.20,608,Pub,1656,Che,1,CHEM,Goods,Aug 1928
Indi_Services,954,733.00,609,Gov,13023,NCR,0,INDI,Services,Mar 1920
Bangalore_Breweries,966,805.00,899,Pvt,119,Blr,1,BREW,Goods,Oct 1971
Bombay_Finance,899,917.00,674,Pub,1443,Mum,0,BFIN,Services,Apr 1925
Chennai_Shipping,992,821.00,665,Pub,899,Che,1,SHIP,Goods,Nov 1930
Eastern_Estates,945,834.23,789,Pvt,1873,Kol,1,EEST,Goods,Jan 1994
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974

In [22]:
df1.loc[df1.Rev>df1.Rev.mean(), ['Rev','Exp']] = 999
df1

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Start Date
Deccan_Sporting,931,839.80,615,Pvt,154,Hyd,1,SPRT,Services,Mar 1943
Kolkata_FMCG,925,999.00,999,Pub,1379,Kol,0,KFMC,Goods,Jan 1920
NCR_Leagles,931,999.00,999,Pub,1935,NCR,0,NCRL,Services,Feb 1960
Bangalore_Systems,900,999.00,999,Gov,1361,Blr,0,BSYS,Services,Apr 1950
Chennai_Chemicals,966,999.00,999,Pub,1656,Che,1,CHEM,Goods,Aug 1928
Indi_Services,954,733.00,609,Gov,13023,NCR,0,INDI,Services,Mar 1920
Bangalore_Breweries,966,805.00,899,Pvt,119,Blr,1,BREW,Goods,Oct 1971
Bombay_Finance,899,999.00,999,Pub,1443,Mum,0,BFIN,Services,Apr 1925
Chennai_Shipping,992,821.00,665,Pub,899,Che,1,SHIP,Goods,Nov 1930
Eastern_Estates,945,834.23,789,Pvt,1873,Kol,1,EEST,Goods,Jan 1994
Central_Services,934,824.00,689,Gov,1573,NCR,1,CSRV,Services,Jun 1974

# sorting 
- ascending/descending

- axis 0 labels - row labels are on axis 0 (rows are on axis 1)

- inplace = true, ensures the orginal df is modified and returns null
    - in python, if object the fn is called upon is modified, then None is returned. else the new modified obj is returned
    <!-- - generally immutable objects have inplace=False and mutable objects have implace=True by default -->

- axis 0 indices are row_labels 
- axis 1 labels are col_labels

In [125]:
df1 = pd.read_csv('./lds_files_v1/lds1.csv')
df1

pd.set_option('display.max_columns', 10)
df2 = df1.sort_index(axis=0, ascending=True, inplace=False)
print(df2)

                     Vol     Rev  Exp Sector  EmpCnt  ... MNC  StockID  \
Bangalore_Breweries  966  875.00  674   Prvt     119  ...   1     BREW
Bangalore_Systems    900  881.60  650    Gov    1361  ...   0     BSYS
Bombay_Finance       954  917.00  665    Pub    1443  ...   0     BFIN
Central_Services     934  824.00  689    Gov    1573  ...   1     CSRV
Chennai_Chemicals    966  863.20  608    Pub    1656  ...   1     CHEM
Chennai_Shipping     899  821.00  899    Pub     899  ...   1     SHIP
Deccan_Sporting      931  839.80  615   Prvt     154  ...   1     SPRT
Eastern_Estates      945  834.23  789   Prvt    1873  ...   1     EEST
Indi_Services        992  733.00  633    Gov   13023  ...   0     INDI
Kolkata_FMCG         925  874.40  676    Pub    1379  ...   0     KFMC
NCR_Infra            921  843.50  615   Prvt    1635  ...   0     NCIN
NCR_Leagles          931  863.50  605    Pub    1935  ...   0     NCRL

                          GST Start Date Taxpaid
Bangalore_Breweries     Goods   Oct 1971  19.65$
Bangalore_Systems    Services   Apr 1950  34.74$
Bombay_Finance       Services   Apr 1925   37.8$
Central_Services     Services   Jun 1974  20.25$
Chennai_Chemicals       Goods   Aug 1928  38.28$
Chennai_Shipping        Goods   Nov 1930       0
Deccan_Sporting      Services   Mar 1943  33.72$
Eastern_Estates         Goods   Jan 1994   6.78$
Indi_Services        Services   Mar 1920     15$
Kolkata_FMCG            Goods   Jan 1920  29.76$
NCR_Infra            Services   Feb 1920  34.27a
NCR_Leagles          Services   Feb 1960  38.78$

[12 rows x 11 columns]

In [24]:
df1.sort_values(by='Vol')
df1.sort_values(by=['Vol', 'Rev'], ascending=[True,False], inplace=False)

,Vol,Rev,Exp,Sector,EmpCnt,...,MNC,StockID,GST,Start Date,Taxpaid
Chennai_Shipping,899,821.00,899,Pub,899,...,1,SHIP,Goods,Nov 1930,0
Bangalore_Systems,900,881.60,650,Gov,1361,...,0,BSYS,Services,Apr 1950,34.74$
NCR_Infra,921,843.50,615,Prvt,1635,...,0,NCIN,Services,Feb 1920,34.27a
Kolkata_FMCG,925,874.40,676,Pub,1379,...,0,KFMC,Goods,Jan 1920,29.76$
NCR_Leagles,931,863.50,605,Pub,1935,...,0,NCRL,Services,Feb 1960,38.78$
Deccan_Sporting,931,839.80,615,Prvt,154,...,1,SPRT,Services,Mar 1943,33.72$
Central_Services,934,824.00,689,Gov,1573,...,1,CSRV,Services,Jun 1974,20.25$
Eastern_Estates,945,834.23,789,Prvt,1873,...,1,EEST,Goods,Jan 1994,6.78$
Bombay_Finance,954,917.00,665,Pub,1443,...,0,BFIN,Services,Apr 1925,37.8$
Bangalore_Breweries,966,875.00,674,Prvt,119,...,1,BREW,Goods,Oct 1971,19.65$
Chennai_Chemicals,966,863.20,608,Pub,1656,...,1,CHEM,Goods,Aug 1928,38.28$
Indi_Services,992,733.00,633,Gov,13023,...,0,INDI,Services,Mar 1920,15$

In [25]:
df1.sort_index(axis=1).sort_values(by='Vol')

,EmpCnt,Exp,GST,HQ,MNC,...,Sector,Start Date,StockID,Taxpaid,Vol
Chennai_Shipping,899,899,Goods,Che,1,...,Pub,Nov 1930,SHIP,0,899
Bangalore_Systems,1361,650,Services,Blr,0,...,Gov,Apr 1950,BSYS,34.74$,900
NCR_Infra,1635,615,Services,NCR,0,...,Prvt,Feb 1920,NCIN,34.27a,921
Kolkata_FMCG,1379,676,Goods,Kol,0,...,Pub,Jan 1920,KFMC,29.76$,925
NCR_Leagles,1935,605,Services,NCR,0,...,Pub,Feb 1960,NCRL,38.78$,931
Deccan_Sporting,154,615,Services,Hyd,1,...,Prvt,Mar 1943,SPRT,33.72$,931
Central_Services,1573,689,Services,NCR,1,...,Gov,Jun 1974,CSRV,20.25$,934
Eastern_Estates,1873,789,Goods,Kol,1,...,Prvt,Jan 1994,EEST,6.78$,945
Bombay_Finance,1443,665,Services,Mum,0,...,Pub,Apr 1925,BFIN,37.8$,954
Chennai_Chemicals,1656,608,Goods,Che,1,...,Pub,Aug 1928,CHEM,38.28$,966
Bangalore_Breweries,119,674,Goods,Blr,1,...,Prvt,Oct 1971,BREW,19.65$,966
Indi_Services,13023,633,Services,NCR,0,...,Gov,Mar 1920,INDI,15$,992

In [26]:
# df1.sort_values(by='Deccan_Sporting', axis=1)
df3 = df1.select_dtypes(include='number')
df3.sort_values(by='Deccan_Sporting', axis=1)
# TODO: sort on Deccan_Sporting row in accending order - use a user defined function for handelling heterogenious values

                     MNC  EmpCnt  Exp     Rev  Vol
Kolkata_FMCG           0    1379  676  874.40  925
NCR_Leagles            0    1935  605  863.50  931
Bangalore_Systems      0    1361  650  881.60  900
Chennai_Chemicals      1    1656  608  863.20  966
Indi_Services          0   13023  633  733.00  992
Chennai_Shipping       1     899  899  821.00  899
Eastern_Estates        1    1873  789  834.23  945
Central_Services       1    1573  689  824.00  934
Deccan_Sporting        1     154  615  839.80  931
Bangalore_Breweries    1     119  674  875.00  966
Bombay_Finance         0    1443  665  917.00  954
NCR_Infra              0    1635  615  843.50  921

# Ranking
          95 80 80 80  75
- dense:  1  2   2  2  3    -> no skip in rank
- first:  1  2   3  4  5    -> continuous numbers
- min:    1  2   2  2  5    -> dense but there is skip in rank
- max:    1  4   4  4  5    -> min but uses the highest value instead of the lowest
- avg:    1  3   3  3  5    -> average value used

In [27]:
df1.Vol.rank()
df1.Vol.rank(ascending=False, method='average')
df1.Vol.rank(ascending=False, method='first')
df1.Vol.rank(ascending=False, method='dense')
df1.Vol.rank(ascending=False, method='min')
df1.Vol.rank(ascending=False, method='max')

Kolkata_FMCG            9.0
NCR_Leagles             8.0
Bangalore_Systems      11.0
Chennai_Chemicals       3.0
Indi_Services           1.0
Chennai_Shipping       12.0
Eastern_Estates         5.0
Central_Services        6.0
Deccan_Sporting         8.0
Bangalore_Breweries     3.0
Bombay_Finance          4.0
NCR_Infra              10.0
Name: Vol, dtype: float64

# group by and pivot table
- used for aggregation
- split into multiple groups, aggregate on columns and combine the results
-

In [28]:
df1.Sector.value_counts()

Sector
Pub     5
Prvt    4
Gov     3
Name: count, dtype: int64

In [29]:
df1.Sector.unique()

array(['Pub', 'Gov', 'Prvt'], dtype=object)

In [30]:
# average revinue across each sector

dfg = df1.groupby(by='Sector') ['Rev'].mean()
# list(dfg)[0]
dfg

Sector
Gov     812.866667
Prvt    848.132500
Pub     867.820000
Name: Rev, dtype: float64

In [31]:
dfg = df1.groupby(by=['Sector', 'GST']) [ ['Rev', 'Exp']  ].mean()
dfg

                        Rev         Exp
Sector GST
Gov    Services  812.866667  657.333333
Prvt   Goods     854.615000  731.500000
       Services  841.650000  615.000000
Pub    Goods     852.866667  727.666667
       Services  890.250000  635.000000

In [32]:
df1.groupby(by='Sector').agg({'Rev': 'mean'})

               Rev
Sector
Gov     812.866667
Prvt    848.132500
Pub     867.820000

In [33]:
df1.groupby(by=['Sector', 'GST']).agg({'Rev': 'mean', 'Exp': 'mean'})

                        Rev         Exp
Sector GST
Gov    Services  812.866667  657.333333
Prvt   Goods     854.615000  731.500000
       Services  841.650000  615.000000
Pub    Goods     852.866667  727.666667
       Services  890.250000  635.000000

loc(<whatever you see in df1.index>, <whatever you see in df1.columns>)

In [34]:
print(df1.index)
print(df1.columns)
df1.loc['Kolkata_FMCG', 'Vol']

Index(['Kolkata_FMCG', 'NCR_Leagles', 'Bangalore_Systems', 'Chennai_Chemicals',
       'Indi_Services', 'Chennai_Shipping', 'Eastern_Estates',
       'Central_Services', 'Deccan_Sporting', 'Bangalore_Breweries',
       'Bombay_Finance', 'NCR_Infra'],
      dtype='object')
Index(['Vol', 'Rev', 'Exp', 'Sector', 'EmpCnt', 'HQ', 'MNC', 'StockID', 'GST',
       'Start Date', 'Taxpaid'],
      dtype='object')

925

In [35]:
print(dfg.index)
print(dfg.columns)
dfg.loc[('Prvt', 'Goods'), 'Rev']

MultiIndex([( 'Gov', 'Services'),
            ('Prvt',    'Goods'),
            ('Prvt', 'Services'),
            ( 'Pub',    'Goods'),
            ( 'Pub', 'Services')],
           names=['Sector', 'GST'])
Index(['Rev', 'Exp'], dtype='object')

854.615

In [36]:
df1.groupby(by=['Sector', 'GST']) [  ['Rev', 'Exp']  ] .agg(['mean', 'max', 'min'])

                        Rev                        Exp
                       mean    max     min        mean  max  min
Sector GST
Gov    Services  812.866667  881.6  733.00  657.333333  689  633
Prvt   Goods     854.615000  875.0  834.23  731.500000  789  674
       Services  841.650000  843.5  839.80  615.000000  615  615
Pub    Goods     852.866667  874.4  821.00  727.666667  899  608
       Services  890.250000  917.0  863.50  635.000000  665  605

In [37]:
def maxMinDif(series):
    return series.max() - series.min()

# maxMinDif = lambda series: series.max()-series.min()

In [128]:
# df1.groupby(by=['Sector', 'GST']) [  ['Rev', 'Exp']  ] .agg(['mean', 'max', 'min', maxMinDif])
df1.groupby(by=['Sector', 'GST']) [  ['Rev', 'Exp']  ] .agg(['mean', 'max', 'min', maxMinDif, lambda series: series.max()-series.min()])

df1.groupby(by='Sector').agg({'Rev':lambda series: series.max()-series.min()})


df1.groupby(by=['Sector', 'GST']).agg({'Rev':lambda series: series.max()-series.min()})

                    Rev
Sector GST
Gov    Services  148.60
Prvt   Goods      40.77
       Services    3.70
Pub    Goods      53.40
       Services   53.50

In [39]:
df1['rank'] = df1.groupby(by='Sector') ['Vol'].rank()
df1

,Vol,Rev,Exp,Sector,EmpCnt,...,StockID,GST,Start Date,Taxpaid,rank
Kolkata_FMCG,925,874.40,676,Pub,1379,...,KFMC,Goods,Jan 1920,29.76$,2.0
NCR_Leagles,931,863.50,605,Pub,1935,...,NCRL,Services,Feb 1960,38.78$,3.0
Bangalore_Systems,900,881.60,650,Gov,1361,...,BSYS,Services,Apr 1950,34.74$,1.0
Chennai_Chemicals,966,863.20,608,Pub,1656,...,CHEM,Goods,Aug 1928,38.28$,5.0
Indi_Services,992,733.00,633,Gov,13023,...,INDI,Services,Mar 1920,15$,3.0
Chennai_Shipping,899,821.00,899,Pub,899,...,SHIP,Goods,Nov 1930,0,1.0
Eastern_Estates,945,834.23,789,Prvt,1873,...,EEST,Goods,Jan 1994,6.78$,3.0
Central_Services,934,824.00,689,Gov,1573,...,CSRV,Services,Jun 1974,20.25$,2.0
Deccan_Sporting,931,839.80,615,Prvt,154,...,SPRT,Services,Mar 1943,33.72$,2.0
Bangalore_Breweries,966,875.00,674,Prvt,119,...,BREW,Goods,Oct 1971,19.65$,4.0
Bombay_Finance,954,917.00,665,Pub,1443,...,BFIN,Services,Apr 1925,37.8$,4.0
NCR_Infra,921,843.50,615,Prvt,1635,...,NCIN,Services,Feb 1920,34.27a,1.0

# pivot table
df1.pivot_table(index="what are the indexes i want(rows i need)", values="coulmn values i want to aggrigate on", agggunc="function fo aggrigation")

In [40]:
dfp = df1.pivot_table(index="Sector", values="Rev", aggfunc="mean")
dfp

               Rev
Sector
Gov     812.866667
Prvt    848.132500
Pub     867.820000

In [41]:
dfp = df1.pivot_table(index=["Sector", "GST"], values=["Rev", "Exp"], 
                      aggfunc=["mean", 'max', maxMinDif])
dfp

                       mean              max        maxMinDif
                        Exp         Rev  Exp    Rev       Exp     Rev
Sector GST
Gov    Services  657.333333  812.866667  689  881.6        56  148.60
Prvt   Goods     731.500000  854.615000  789  875.0       115   40.77
       Services  615.000000  841.650000  615  843.5         0    3.70
Pub    Goods     727.666667  852.866667  899  874.4       291   53.40
       Services  635.000000  890.250000  665  917.0        60   53.50

In [42]:
pd.crosstab(df1.Sector, df1.GST)
df1.pivot_table(index='Sector', columns='GST', values='Rev', aggfunc='count')

GST     Goods  Services
Sector
Gov       NaN       3.0
Prvt      2.0       2.0
Pub       3.0       2.0

In [43]:
df1.HQ.unique()

array(['Kol', 'NCR', 'Blr', 'Che', 'Hyd', 'Mum'], dtype=object)

In [44]:
md1 = {
    'Kol':'ez',
    'NCR': 'nz',
    'Blr':'sz',
    'Che':'sz',
    'Hyd':'sz',
    'mum':'wz'
}

df1['Zone'] = df1.HQ.map(md1)
df1

,Vol,Rev,Exp,Sector,EmpCnt,...,GST,Start Date,Taxpaid,rank,Zone
Kolkata_FMCG,925,874.40,676,Pub,1379,...,Goods,Jan 1920,29.76$,2.0,ez
NCR_Leagles,931,863.50,605,Pub,1935,...,Services,Feb 1960,38.78$,3.0,nz
Bangalore_Systems,900,881.60,650,Gov,1361,...,Services,Apr 1950,34.74$,1.0,sz
Chennai_Chemicals,966,863.20,608,Pub,1656,...,Goods,Aug 1928,38.28$,5.0,sz
Indi_Services,992,733.00,633,Gov,13023,...,Services,Mar 1920,15$,3.0,nz
Chennai_Shipping,899,821.00,899,Pub,899,...,Goods,Nov 1930,0,1.0,sz
Eastern_Estates,945,834.23,789,Prvt,1873,...,Goods,Jan 1994,6.78$,3.0,ez
Central_Services,934,824.00,689,Gov,1573,...,Services,Jun 1974,20.25$,2.0,nz
Deccan_Sporting,931,839.80,615,Prvt,154,...,Services,Mar 1943,33.72$,2.0,sz
Bangalore_Breweries,966,875.00,674,Prvt,119,...,Goods,Oct 1971,19.65$,4.0,sz
Bombay_Finance,954,917.00,665,Pub,1443,...,Services,Apr 1925,37.8$,4.0,NaN
NCR_Infra,921,843.50,615,Prvt,1635,...,Services,Feb 1920,34.27a,1.0,nz

In [45]:
df1.Taxpaid.dtype

dtype('O')

In [46]:
# data cleaning
df1['Taxpaid'] = df1.Taxpaid.map(lambda ms1: float(ms1.replace("$", "").replace("a", "")))
# df1['Taxpaid'].str.replace('$','').str.replace('a','').astype('float')

In [47]:
df1.drop(index=['NCR_Infra', 'Bombay_Finance'], columns=['Sector'], inplace=False)

,Vol,Rev,Exp,EmpCnt,HQ,...,GST,Start Date,Taxpaid,rank,Zone
Kolkata_FMCG,925,874.40,676,1379,Kol,...,Goods,Jan 1920,29.76,2.0,ez
NCR_Leagles,931,863.50,605,1935,NCR,...,Services,Feb 1960,38.78,3.0,nz
Bangalore_Systems,900,881.60,650,1361,Blr,...,Services,Apr 1950,34.74,1.0,sz
Chennai_Chemicals,966,863.20,608,1656,Che,...,Goods,Aug 1928,38.28,5.0,sz
Indi_Services,992,733.00,633,13023,NCR,...,Services,Mar 1920,15.00,3.0,nz
Chennai_Shipping,899,821.00,899,899,Che,...,Goods,Nov 1930,0.00,1.0,sz
Eastern_Estates,945,834.23,789,1873,Kol,...,Goods,Jan 1994,6.78,3.0,ez
Central_Services,934,824.00,689,1573,NCR,...,Services,Jun 1974,20.25,2.0,nz
Deccan_Sporting,931,839.80,615,154,Hyd,...,Services,Mar 1943,33.72,2.0,sz
Bangalore_Breweries,966,875.00,674,119,Blr,...,Goods,Oct 1971,19.65,4.0,sz

In [48]:
if 'NCR_Infra' in df1.index:
    dfg = df1.drop(index=['NCR_Infra'], inplace=False)
else:
    print("label not found")
dfg

,Vol,Rev,Exp,Sector,EmpCnt,...,GST,Start Date,Taxpaid,rank,Zone
Kolkata_FMCG,925,874.40,676,Pub,1379,...,Goods,Jan 1920,29.76,2.0,ez
NCR_Leagles,931,863.50,605,Pub,1935,...,Services,Feb 1960,38.78,3.0,nz
Bangalore_Systems,900,881.60,650,Gov,1361,...,Services,Apr 1950,34.74,1.0,sz
Chennai_Chemicals,966,863.20,608,Pub,1656,...,Goods,Aug 1928,38.28,5.0,sz
Indi_Services,992,733.00,633,Gov,13023,...,Services,Mar 1920,15.00,3.0,nz
Chennai_Shipping,899,821.00,899,Pub,899,...,Goods,Nov 1930,0.00,1.0,sz
Eastern_Estates,945,834.23,789,Prvt,1873,...,Goods,Jan 1994,6.78,3.0,ez
Central_Services,934,824.00,689,Gov,1573,...,Services,Jun 1974,20.25,2.0,nz
Deccan_Sporting,931,839.80,615,Prvt,154,...,Services,Mar 1943,33.72,2.0,sz
Bangalore_Breweries,966,875.00,674,Prvt,119,...,Goods,Oct 1971,19.65,4.0,sz
Bombay_Finance,954,917.00,665,Pub,1443,...,Services,Apr 1925,37.80,4.0,NaN

# renaming of labels

In [49]:
df1.rename(index={'Bombay_Finance': 'BF',"Bangalore_Breweries": "BB"},
           columns={'Rev':'revinue'},
           inplace=False, errors='ignore')

,Vol,revinue,Exp,Sector,EmpCnt,...,GST,Start Date,Taxpaid,rank,Zone
Kolkata_FMCG,925,874.40,676,Pub,1379,...,Goods,Jan 1920,29.76,2.0,ez
NCR_Leagles,931,863.50,605,Pub,1935,...,Services,Feb 1960,38.78,3.0,nz
Bangalore_Systems,900,881.60,650,Gov,1361,...,Services,Apr 1950,34.74,1.0,sz
Chennai_Chemicals,966,863.20,608,Pub,1656,...,Goods,Aug 1928,38.28,5.0,sz
Indi_Services,992,733.00,633,Gov,13023,...,Services,Mar 1920,15.00,3.0,nz
Chennai_Shipping,899,821.00,899,Pub,899,...,Goods,Nov 1930,0.00,1.0,sz
Eastern_Estates,945,834.23,789,Prvt,1873,...,Goods,Jan 1994,6.78,3.0,ez
Central_Services,934,824.00,689,Gov,1573,...,Services,Jun 1974,20.25,2.0,nz
Deccan_Sporting,931,839.80,615,Prvt,154,...,Services,Mar 1943,33.72,2.0,sz
BB,966,875.00,674,Prvt,119,...,Goods,Oct 1971,19.65,4.0,sz
BF,954,917.00,665,Pub,1443,...,Services,Apr 1925,37.80,4.0,NaN
NCR_Infra,921,843.50,615,Prvt,1635,...,Services,Feb 1920,34.27,1.0,nz

# replace of values

In [50]:
df1.Sector.replace({'Pub': 'Public', 'Prvt': 'Private'})

Kolkata_FMCG            Public
NCR_Leagles             Public
Bangalore_Systems          Gov
Chennai_Chemicals       Public
Indi_Services              Gov
Chennai_Shipping        Public
Eastern_Estates        Private
Central_Services           Gov
Deccan_Sporting        Private
Bangalore_Breweries    Private
Bombay_Finance          Public
NCR_Infra              Private
Name: Sector, dtype: object

# RW file formats

In [51]:
import os
os.getcwd()
df1.to_csv('file1.csv')
df1.to_excel('file2.xlsx')
df1.to_json('file3.json')
df1.to_html('file4.html')

In [52]:
f1 = pd.read_csv('file1.csv')

f1

,Unnamed: 0,Vol,Rev,Exp,Sector,...,GST,Start Date,Taxpaid,rank,Zone
0,Kolkata_FMCG,925,874.40,676,Pub,...,Goods,Jan 1920,29.76,2.0,ez
1,NCR_Leagles,931,863.50,605,Pub,...,Services,Feb 1960,38.78,3.0,nz
2,Bangalore_Systems,900,881.60,650,Gov,...,Services,Apr 1950,34.74,1.0,sz
3,Chennai_Chemicals,966,863.20,608,Pub,...,Goods,Aug 1928,38.28,5.0,sz
4,Indi_Services,992,733.00,633,Gov,...,Services,Mar 1920,15.00,3.0,nz
5,Chennai_Shipping,899,821.00,899,Pub,...,Goods,Nov 1930,0.00,1.0,sz
6,Eastern_Estates,945,834.23,789,Prvt,...,Goods,Jan 1994,6.78,3.0,ez
7,Central_Services,934,824.00,689,Gov,...,Services,Jun 1974,20.25,2.0,nz
8,Deccan_Sporting,931,839.80,615,Prvt,...,Services,Mar 1943,33.72,2.0,sz
9,Bangalore_Breweries,966,875.00,674,Prvt,...,Goods,Oct 1971,19.65,4.0,sz
10,Bombay_Finance,954,917.00,665,Pub,...,Services,Apr 1925,37.80,4.0,NaN
11,NCR_Infra,921,843.50,615,Prvt,...,Services,Feb 1920,34.27,1.0,nz

In [53]:
f1 = pd.read_csv('file1.csv', index_col=0)
f1

,Vol,Rev,Exp,Sector,EmpCnt,...,GST,Start Date,Taxpaid,rank,Zone
Kolkata_FMCG,925,874.40,676,Pub,1379,...,Goods,Jan 1920,29.76,2.0,ez
NCR_Leagles,931,863.50,605,Pub,1935,...,Services,Feb 1960,38.78,3.0,nz
Bangalore_Systems,900,881.60,650,Gov,1361,...,Services,Apr 1950,34.74,1.0,sz
Chennai_Chemicals,966,863.20,608,Pub,1656,...,Goods,Aug 1928,38.28,5.0,sz
Indi_Services,992,733.00,633,Gov,13023,...,Services,Mar 1920,15.00,3.0,nz
Chennai_Shipping,899,821.00,899,Pub,899,...,Goods,Nov 1930,0.00,1.0,sz
Eastern_Estates,945,834.23,789,Prvt,1873,...,Goods,Jan 1994,6.78,3.0,ez
Central_Services,934,824.00,689,Gov,1573,...,Services,Jun 1974,20.25,2.0,nz
Deccan_Sporting,931,839.80,615,Prvt,154,...,Services,Mar 1943,33.72,2.0,sz
Bangalore_Breweries,966,875.00,674,Prvt,119,...,Goods,Oct 1971,19.65,4.0,sz
Bombay_Finance,954,917.00,665,Pub,1443,...,Services,Apr 1925,37.80,4.0,NaN
NCR_Infra,921,843.50,615,Prvt,1635,...,Services,Feb 1920,34.27,1.0,nz

In [54]:
f1 = pd.read_excel('file2.xlsx', index_col=0)
f1 = pd.read_json('file3.json')
listOfFrames = pd.read_html('file4.html', index_col=0)
listOfFrames[0]

,Vol,Rev,Exp,Sector,EmpCnt,...,GST,Start Date,Taxpaid,rank,Zone
Kolkata_FMCG,925,874.40,676,Pub,1379,...,Goods,Jan 1920,29.76,2.0,ez
NCR_Leagles,931,863.50,605,Pub,1935,...,Services,Feb 1960,38.78,3.0,nz
Bangalore_Systems,900,881.60,650,Gov,1361,...,Services,Apr 1950,34.74,1.0,sz
Chennai_Chemicals,966,863.20,608,Pub,1656,...,Goods,Aug 1928,38.28,5.0,sz
Indi_Services,992,733.00,633,Gov,13023,...,Services,Mar 1920,15.00,3.0,nz
Chennai_Shipping,899,821.00,899,Pub,899,...,Goods,Nov 1930,0.00,1.0,sz
Eastern_Estates,945,834.23,789,Prvt,1873,...,Goods,Jan 1994,6.78,3.0,ez
Central_Services,934,824.00,689,Gov,1573,...,Services,Jun 1974,20.25,2.0,nz
Deccan_Sporting,931,839.80,615,Prvt,154,...,Services,Mar 1943,33.72,2.0,sz
Bangalore_Breweries,966,875.00,674,Prvt,119,...,Goods,Oct 1971,19.65,4.0,sz
Bombay_Finance,954,917.00,665,Pub,1443,...,Services,Apr 1925,37.80,4.0,NaN
NCR_Infra,921,843.50,615,Prvt,1635,...,Services,Feb 1920,34.27,1.0,nz

# missing data / NaN handling

In [55]:
df0 = pd.read_csv('./lds_files_v1/lds0.csv')

In [56]:
df0.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Deccan_Sporting to Eastern_Estates
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Vol      10 non-null     int64
 1   Rev      6 non-null      float64
 2   Exp      10 non-null     int64
 3   Sector   6 non-null      object
 4   EmpCnt   8 non-null      float64
 5   HQ       9 non-null      object
 6   MNC      10 non-null     int64
 7   StockID  10 non-null     object
 8   GST      10 non-null     object
 9   Started  10 non-null     object
dtypes: float64(2), int64(3), object(5)
memory usage: 880.0+ bytes

In [57]:
df0.isna()

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Started
Deccan_Sporting,False,False,False,False,True,False,False,False,False,False
Kolkata_FMCG,False,True,False,True,False,False,False,False,False,False
NCR_Leagles,False,False,False,True,False,False,False,False,False,False
Bangalore_Systems,False,True,False,False,False,False,False,False,False,False
Chennai_Chemicals,False,False,False,False,False,False,False,False,False,False
Indi_Services,False,False,False,False,False,False,False,False,False,False
Bangalore_Breweries,False,True,False,True,False,False,False,False,False,False
Bombay_Finance,False,True,False,False,True,False,False,False,False,False
Chennai_Shipping,False,False,False,True,False,False,False,False,False,False
Eastern_Estates,False,False,False,False,False,True,False,False,False,False

In [58]:
df0.isna().sum() # True = 1 false = 0

Vol        0
Rev        4
Exp        0
Sector     4
EmpCnt     2
HQ         1
MNC        0
StockID    0
GST        0
Started    0
dtype: int64

In [59]:
df0.isna().sum().sum()

11

In [60]:
df0.dropna()

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Started
Chennai_Chemicals,966,863.2,608,Pub,1656.0,Che,1,CHEM,Goods,Aug 1928
Indi_Services,954,733.0,609,Gov,13023.0,NCR,0,INDI,Services,Mar 1920

In [61]:
df0.fillna(888)

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Started
Deccan_Sporting,931,839.80,615,Pvt,888.0,Hyd,1,SPRT,Services,Mar 1943
Kolkata_FMCG,925,888.00,676,888,1379.0,Kol,0,KFMC,Goods,Jan 1920
NCR_Leagles,931,863.50,605,888,1935.0,NCR,0,NCRL,Services,Feb 1960
Bangalore_Systems,900,888.00,650,Gov,1361.0,Blr,0,BSYS,Services,Apr 1950
Chennai_Chemicals,966,863.20,608,Pub,1656.0,Che,1,CHEM,Goods,Aug 1928
Indi_Services,954,733.00,609,Gov,13023.0,NCR,0,INDI,Services,Mar 1920
Bangalore_Breweries,966,888.00,895,888,119.0,Blr,1,BREW,Goods,Oct 1971
Bombay_Finance,899,888.00,674,Pub,888.0,Mum,0,BFIN,Services,Apr 1925
Chennai_Shipping,992,821.00,665,888,1154.0,Che,1,SHIP,Goods,Nov 1930
Eastern_Estates,945,834.23,789,Pvt,1873.0,888,1,EEST,Goods,Jan 1994

In [62]:
df0.Rev.mean()

825.7883333333333

In [63]:
df0.Rev = df0.Rev.fillna(df0.Rev.mean())
df0

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Started
Deccan_Sporting,931,839.800000,615,Pvt,NaN,Hyd,1,SPRT,Services,Mar 1943
Kolkata_FMCG,925,825.788333,676,NaN,1379.0,Kol,0,KFMC,Goods,Jan 1920
NCR_Leagles,931,863.500000,605,NaN,1935.0,NCR,0,NCRL,Services,Feb 1960
Bangalore_Systems,900,825.788333,650,Gov,1361.0,Blr,0,BSYS,Services,Apr 1950
Chennai_Chemicals,966,863.200000,608,Pub,1656.0,Che,1,CHEM,Goods,Aug 1928
Indi_Services,954,733.000000,609,Gov,13023.0,NCR,0,INDI,Services,Mar 1920
Bangalore_Breweries,966,825.788333,895,NaN,119.0,Blr,1,BREW,Goods,Oct 1971
Bombay_Finance,899,825.788333,674,Pub,NaN,Mum,0,BFIN,Services,Apr 1925
Chennai_Shipping,992,821.000000,665,NaN,1154.0,Che,1,SHIP,Goods,Nov 1930
Eastern_Estates,945,834.230000,789,Pvt,1873.0,NaN,1,EEST,Goods,Jan 1994

In [64]:
df0.EmpCnt.median()

1517.5

In [65]:
df0.ffill()

,Vol,Rev,Exp,Sector,EmpCnt,HQ,MNC,StockID,GST,Started
Deccan_Sporting,931,839.800000,615,Pvt,NaN,Hyd,1,SPRT,Services,Mar 1943
Kolkata_FMCG,925,825.788333,676,Pvt,1379.0,Kol,0,KFMC,Goods,Jan 1920
NCR_Leagles,931,863.500000,605,Pvt,1935.0,NCR,0,NCRL,Services,Feb 1960
Bangalore_Systems,900,825.788333,650,Gov,1361.0,Blr,0,BSYS,Services,Apr 1950
Chennai_Chemicals,966,863.200000,608,Pub,1656.0,Che,1,CHEM,Goods,Aug 1928
Indi_Services,954,733.000000,609,Gov,13023.0,NCR,0,INDI,Services,Mar 1920
Bangalore_Breweries,966,825.788333,895,Gov,119.0,Blr,1,BREW,Goods,Oct 1971
Bombay_Finance,899,825.788333,674,Pub,119.0,Mum,0,BFIN,Services,Apr 1925
Chennai_Shipping,992,821.000000,665,Pub,1154.0,Che,1,SHIP,Goods,Nov 1930
Eastern_Estates,945,834.230000,789,Pvt,1873.0,Che,1,EEST,Goods,Jan 1994

In [66]:
df0.Sector.bfill()

Deccan_Sporting        Pvt
Kolkata_FMCG           Gov
NCR_Leagles            Gov
Bangalore_Systems      Gov
Chennai_Chemicals      Pub
Indi_Services          Gov
Bangalore_Breweries    Pub
Bombay_Finance         Pub
Chennai_Shipping       Pvt
Eastern_Estates        Pvt
Name: Sector, dtype: object

In [67]:
df0.HQ.bfill() # last NaN not handled by bfill

Deccan_Sporting        Hyd
Kolkata_FMCG           Kol
NCR_Leagles            NCR
Bangalore_Systems      Blr
Chennai_Chemicals      Che
Indi_Services          NCR
Bangalore_Breweries    Blr
Bombay_Finance         Mum
Chennai_Shipping       Che
Eastern_Estates        NaN
Name: HQ, dtype: object

In [68]:
df0.HQ.bfill().ffill()

Deccan_Sporting        Hyd
Kolkata_FMCG           Kol
NCR_Leagles            NCR
Bangalore_Systems      Blr
Chennai_Chemicals      Che
Indi_Services          NCR
Bangalore_Breweries    Blr
Bombay_Finance         Mum
Chennai_Shipping       Che
Eastern_Estates        Che
Name: HQ, dtype: object

# Duplicate handling

In [69]:
df33 = pd.read_csv('lds_files_v1/lds33.csv')
df33

        Date    City  Temperature  Humidity
0  15/1/2019  Shimla           11        67
1  15/2/2019  Shimla           12        65
2  15/3/2019  Shimla           11        57
3  15/1/2019  Shimla           11        67
4  15/1/2019    Pune           29        34
5  15/2/2019    Pune           32        26
6  15/1/2020    Pune           29        21
7  15/1/2019  Mysore           28        49
8  15/2/2019  Mysore           31        47
9  15/1/2020  Mysore           33        49

In [70]:
df33.duplicated()
df33.duplicated(subset=None, keep='first')

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [71]:
df33.duplicated(subset=None, keep='last')

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [72]:
df33.duplicated(subset=None, keep=False)

0     True
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [73]:
df33[df33.duplicated(subset=None, keep=False)]

        Date    City  Temperature  Humidity
0  15/1/2019  Shimla           11        67
3  15/1/2019  Shimla           11        67

In [74]:
# ~ is the BITWISE invert operator (not operator)
df33[~df33.duplicated(subset=None, keep=False)]

        Date    City  Temperature  Humidity
1  15/2/2019  Shimla           12        65
2  15/3/2019  Shimla           11        57
4  15/1/2019    Pune           29        34
5  15/2/2019    Pune           32        26
6  15/1/2020    Pune           29        21
7  15/1/2019  Mysore           28        49
8  15/2/2019  Mysore           31        47
9  15/1/2020  Mysore           33        49

In [75]:
df33.drop_duplicates(subset=None, keep=False, inplace=False)

        Date    City  Temperature  Humidity
1  15/2/2019  Shimla           12        65
2  15/3/2019  Shimla           11        57
4  15/1/2019    Pune           29        34
5  15/2/2019    Pune           32        26
6  15/1/2020    Pune           29        21
7  15/1/2019  Mysore           28        49
8  15/2/2019  Mysore           31        47
9  15/1/2020  Mysore           33        49

In [76]:
df33.drop_duplicates(subset=['City','Temperature'], keep=False, inplace=False)

        Date    City  Temperature  Humidity
1  15/2/2019  Shimla           12        65
5  15/2/2019    Pune           32        26
7  15/1/2019  Mysore           28        49
8  15/2/2019  Mysore           31        47
9  15/1/2020  Mysore           33        49

# concat

In [77]:
df11 = pd.read_csv('lds_files_v1/lds11.csv')
df12 = pd.read_csv('lds_files_v1/lds12.csv')
df13 = pd.read_csv('lds_files_v1/lds13.csv')

In [78]:
# axis 0 is vertical stacking
# inner - intersection # outer - union
dfc = pd.concat(objs=[df11,df12], axis=0, join='inner', keys=None)
dfc

                   Vol    Rev  Exp Sector
Kolkata_FMCG       900  874.4  676    Pub
NCR_Leagles        931  863.5  605    Pub
Bombay_Sporting    975  839.8  615    Pvt
Bombay_Sporting    925  839.8  715    Pvt
Bombay_Finance     899  917.0  674    Pub
Bangalore_Systems  931  881.6  650    Gov
Chennai_Shipping   992  821.0  665    Pub

In [79]:
dfc = pd.concat(objs=[df11,df12], axis=0, join='outer', keys=['f11', 'f12'])
dfc

                       Vol    Rev  Exp Sector  EmpCnt   HQ
f11 Kolkata_FMCG       900  874.4  676    Pub  1379.0  NaN
    NCR_Leagles        931  863.5  605    Pub  1935.0  NaN
    Bombay_Sporting    975  839.8  615    Pvt   154.0  NaN
f12 Bombay_Sporting    925  839.8  715    Pvt     NaN  Mum
    Bombay_Finance     899  917.0  674    Pub     NaN  Mum
    Bangalore_Systems  931  881.6  650    Gov     NaN  Blr
    Chennai_Shipping   992  821.0  665    Pub     NaN  Che

In [80]:
dfc = pd.concat(objs=[df11,df12], axis=1, join='inner', keys=None)
dfc

                 Vol    Rev  Exp Sector  EmpCnt  Vol    Rev  Exp Sector   HQ
Bombay_Sporting  975  839.8  615    Pvt     154  925  839.8  715    Pvt  Mum

In [81]:
dfc = pd.concat(objs=[df11,df12,df13], axis=1, join='inner', keys=None)
dfc

Empty DataFrame
Columns: [Vol, Rev, Exp, Sector, EmpCnt, Vol, Rev, Exp, Sector, HQ, Vol, Rev, Exp, Sector, EmpCnt, HQ]
Index: []

[0 rows x 16 columns]

In [82]:
dfc = pd.concat(objs=[df11,df12,df13], axis=0, join='inner', keys=None)
dfc

                     Vol    Rev  Exp Sector
Kolkata_FMCG         900  874.4  676    Pub
NCR_Leagles          931  863.5  605    Pub
Bombay_Sporting      975  839.8  615    Pvt
Bombay_Sporting      925  839.8  715    Pvt
Bombay_Finance       899  917.0  674    Pub
Bangalore_Systems    931  881.6  650    Gov
Chennai_Shipping     992  821.0  665    Pub
Bangalore_Breweries  966  805.0  895    Pvt
Chennai_Chemicals    966  863.2  608    Pub
Indi_Services        954  733.0  609    Gov

# merge

In [83]:
df21 = pd.read_csv("lds_files_v1/lds21.csv")
df22 = pd.read_csv("lds_files_v1/lds22.csv")
df23 = pd.read_csv("lds_files_v1/lds23.csv")

print(df21)
print(df22)
print(df23)

                    stock_id   HQ  high
Bangalore_Breweries     BREW  Blr  1100
Chennai_Shipping        SHIP  Che  1200
Kolkata_FMCG            KFMC  Kol  2000
NCR_Leagles             NCRL  NCR  1200
                    stock_name   HQ  vol
Bangalore_Breweries       BREW  Blr  350
Bombay_Finance            BFIN  Mum  450
Chennai_Chemicals         CHEM  Che  550
Kolkata_FMCG              KFMC  Kol  500
                    stock_name   HQ  empcnt
Chennai_Shipping          SHIP  Che   10000
Bangalore_Breweries       BREW  Blr    5000
Bombay_Finance            BFIN  Mum   30000
Bangalore_Systems         BSYS  Blr   20000

In [84]:
dfm = pd.merge(left=df21, right=df22, how='inner', on='HQ', indicator=True)
dfm = pd.merge(left=df21, right=df22, how='cross', indicator=True)  # no 'on' parameter for cross
dfm = pd.merge(left=df21, right=df22, how='outer', on='HQ', indicator=True)


dfm

  stock_id   HQ    high stock_name    vol      _merge
0     BREW  Blr  1100.0       BREW  350.0        both
1     SHIP  Che  1200.0       CHEM  550.0        both
2     KFMC  Kol  2000.0       KFMC  500.0        both
3      NaN  Mum     NaN       BFIN  450.0  right_only
4     NCRL  NCR  1200.0        NaN    NaN   left_only

In [85]:
print(df21)
print(df22)
print(df23)

dfm = pd.merge(left=df21, right=df22, how='inner', left_on='stock_id', right_on='stock_name',
               suffixes=['_left', '_right'], indicator=True)

dfm

                    stock_id   HQ  high
Bangalore_Breweries     BREW  Blr  1100
Chennai_Shipping        SHIP  Che  1200
Kolkata_FMCG            KFMC  Kol  2000
NCR_Leagles             NCRL  NCR  1200
                    stock_name   HQ  vol
Bangalore_Breweries       BREW  Blr  350
Bombay_Finance            BFIN  Mum  450
Chennai_Chemicals         CHEM  Che  550
Kolkata_FMCG              KFMC  Kol  500
                    stock_name   HQ  empcnt
Chennai_Shipping          SHIP  Che   10000
Bangalore_Breweries       BREW  Blr    5000
Bombay_Finance            BFIN  Mum   30000
Bangalore_Systems         BSYS  Blr   20000

  stock_id HQ_left  high stock_name HQ_right  vol _merge
0     BREW     Blr  1100       BREW      Blr  350   both
1     KFMC     Kol  2000       KFMC      Kol  500   both

In [86]:
df21.join(df22, lsuffix='_x', rsuffix='_y') # default left outer join

# difference bw join and merge?

                    stock_id HQ_x  high stock_name HQ_y    vol
Bangalore_Breweries     BREW  Blr  1100       BREW  Blr  350.0
Chennai_Shipping        SHIP  Che  1200        NaN  NaN    NaN
Kolkata_FMCG            KFMC  Kol  2000       KFMC  Kol  500.0
NCR_Leagles             NCRL  NCR  1200        NaN  NaN    NaN

# multilevel indexed data frame
- we are trying to reshape the df

In [87]:
np.random.seed(23)
n84 = np.random.randint(low=10, high=100, size=(8,4))
n84

array([[93, 50, 83, 64],
       [41, 86, 49, 35],
       [61, 16, 55, 22],
       [59, 76, 85, 95],
       [79, 74, 22, 31],
       [58, 51, 89, 72],
       [67, 29, 43, 69],
       [49, 25, 46, 75]])

# stack
- source level can be chosen but destination level is always -1 or closest to data
- topmost header is index 0 and the header closest to data is index -1

In [88]:
col_level0_labels = [2022,2023]
col_level1_labels = ['q1','q2']
col_labels = pd.MultiIndex.from_product([col_level0_labels, col_level1_labels])

row_level0_labels = ['tata', 'birla', 'wipro', 'itc']
row_level1_labels = ['fmcg', 'tech']
row_labels = pd.MultiIndex.from_product([row_level0_labels, row_level1_labels])

df1 = pd.DataFrame(n84, index=row_labels, columns=col_labels)
df1

           2022     2023
             q1  q2   q1  q2
tata  fmcg   93  50   83  64
      tech   41  86   49  35
birla fmcg   61  16   55  22
      tech   59  76   85  95
wipro fmcg   79  74   22  31
      tech   58  51   89  72
itc   fmcg   67  29   43  69
      tech   49  25   46  75

In [89]:
df1.stack(future_stack=True)
# df1.unstack(1).unstack()
# df1.unstack(-1)

df1.stack().stack().unstack(0).unstack(-1)

C:\Users\ashwi\AppData\Local\Temp\ipykernel_6848\4274417394.py:5: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df1.stack().stack().unstack(0).unstack(-1)

        birla       itc      tata      wipro
         2022 2023 2022 2023 2022 2023  2022 2023
fmcg q1    61   55   67   43   93   83    79   22
     q2    16   22   29   69   50   64    74   31
tech q1    59   85   49   46   41   49    58   89
     q2    76   95   25   75   86   35    51   72

In [90]:
df1.unstack(1)

      2022                2023
        q1        q2        q1        q2
      fmcg tech fmcg tech fmcg tech fmcg tech
birla   61   59   16   76   55   85   22   95
itc     67   49   29   25   43   46   69   75
tata    93   41   50   86   83   49   64   35
wipro   79   58   74   51   22   89   31   72

In [91]:
import math
import random
totalCnt = 0
resCnt = 0

for i in range(1000000000):
    a = math.floor(random.random() * 10)
    b = math.floor(random.random() * 10)
    if(a==0 or b==0 or a>6 or b>6):
        continue

    totalCnt+=1
    if a+b==7:
        resCnt+=1


resCnt/totalCnt

KeyboardInterrupt: